version: '3.8'

services:
  # 1. React + Nginx
  frontend:
    build:
      context: ./source/frontend
      dockerfile: Dockerfile
    container_name: frontend_app
    ports:
      - '8080:80'
    restart: unless-stopped
    networks:
      - geopathplanner-net

  user-management:
    build:
      context: ./source/user-management
      dockerfile: Dockerfile.dev
    container_name: user_management_app
    restart: unless-stopped
    environment:
      NODE_ENV: development
      PORT: 3000
      DB_HOST: db # db on sharednetwork
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: Juventus108
      DB_NAME: user_auth_db
      JWT_SECRET: 4dad8f6ac14402c48cdd26c8c16da04f00e82a47d9e988d8597e718e7d65e6e8
      JWT_EXPIRATION: 7d
    ports:
      - '3000:3000'
    volumes:
      - ./source/user-management/src:/app/src
      - ./source/user-management/test:/app/test
      - /app/node_modules
    depends_on:
      db:
        condition: service_healthy
    networks:
      - geopathplanner-net

  # 3. PostgreSQL
  db:
    image: postgres:15-alpine
    container_name: postgres_db_user_management
    restart: unless-stopped
    environment:
      POSTGRES_DB: user_auth_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Juventus108
      TZ: 'Europe/Rome'
    ports:
      - '5433:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - geopathplanner-net

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin123
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - '5050:80'
    depends_on:
      - db
    networks:
      - geopathplanner-net

# Define the shared network
networks:
  geopathplanner-net:
    driver: bridge

# Define persistent volumes
volumes:
  postgres_data:
    driver: local
