version: '3.8'

services:
  routing:
    image: geopathplanner/routing:latest
    build:
      context: routing
      dockerfile: Dockerfile
    deploy:
      mode: replicated
      replicas: ${KAFKA_REQUEST_TOPIC_PARTITIONS}
    env_file:
      - .env
    depends_on:
      kafka-init-topics:
        condition: service_completed_successfully
      api:
        condition: service_healthy
    networks:
      - geopathplanner-net

  api:
    image: geopathplanner/api:latest
    build:
      context: api
      dockerfile: Dockerfile
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://0.0.0.0:8000/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
      kafka-init-topics:
        condition: service_completed_successfully
    ports:
      - "8000:8000"
    networks:
      - geopathplanner-net

  db:
    container_name: db
    restart: always
    image: postgis/postgis:16-3.4
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5433:${POSTGRES_CONTAINER_PORT}"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d ${POSTGRES_DB} -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 60s
      retries: 5
      start_period: 10s
    volumes:
      - api_db_data:/var/lib/postgresql/data
    networks:
      - geopathplanner-net

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: user-name@domain-name.com
      PGADMIN_DEFAULT_PASSWORD: strong-password
    volumes:
      - api_pgadmin_data:/var/lib/pgadmin
    networks:
      - geopathplanner-net
    depends_on:
      - db

  kafka:
    image: apache/kafka:latest
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "/opt/kafka/bin/kafka-cluster.sh cluster-id --bootstrap-server :9092 || exit 1",
        ]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 15s
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_LISTENERS: CONTROLLER://localhost:9091,HOST://0.0.0.0:9092,DOCKER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: HOST://localhost:9092,DOCKER://kafka:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,DOCKER:PLAINTEXT,HOST:PLAINTEXT
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9091
      KAFKA_INTER_BROKER_LISTENER_NAME: DOCKER
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_NUM_PARTITIONS: ${KAFKA_REQUEST_TOPIC_PARTITIONS}
    networks:
      - geopathplanner-net

  kafka-init-topics:
    image: apache/kafka:latest
    container_name: kafka-init-topics
    depends_on:
      kafka:
        condition: service_healthy
        restart: true
    entrypoint: >
      bash -c "
      echo 'Waiting for Kafka to be ready...';
      /opt/kafka/bin/kafka-topics.sh --bootstrap-server ${KAFKA_BROKERS} --create --if-not-exists --topic ${KAFKA_REQUEST_TOPIC} --partitions ${KAFKA_REQUEST_TOPIC_PARTITIONS};
      /opt/kafka/bin/kafka-topics.sh --bootstrap-server ${KAFKA_BROKERS} --create --if-not-exists --topic ${KAFKA_RESPONSE_TOPIC} --partitions ${KAFKA_RESPONSE_TOPIC_PARTITIONS};
      echo 'Topics created successfully!';
      "
    networks:
      - geopathplanner-net

  kafka-ui:
    image: kafbat/kafka-ui:main
    container_name: kafka-ui
    ports:
      - "8080:8080"
    environment:
      DYNAMIC_CONFIG_ENABLED: "true"
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: ${KAFKA_BROKERS}
    depends_on:
      kafka:
        condition: service_healthy
        restart: true
    networks:
      - geopathplanner-net

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend_app
    ports:
      - '8081:80'
    restart: unless-stopped
    networks:
      - geopathplanner-net

  user-management:
    build:
      context: ./user-management
      dockerfile: Dockerfile.dev
    container_name: user_management_app
    restart: unless-stopped
    environment:
      NODE_ENV: development
      PORT: 3000
      DB_HOST: user-management-db
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: Juventus108
      DB_NAME: user_auth_db
      JWT_SECRET: 4dad8f6ac14402c48cdd26c8c16da04f00e82a47d9e988d8597e718e7d65e6e8
      JWT_EXPIRATION: 7d
    ports:
      - '3000:3000'
    volumes:
      - ./user-management/src:/app/src
      - ./user-management/test:/app/test
      - /app/node_modules
    depends_on:
      user-management-db:
        condition: service_healthy
    networks:
      - geopathplanner-net

  user-management-db:
    image: postgres:15-alpine
    container_name: postgres_db_user_management
    restart: unless-stopped
    environment:
      POSTGRES_DB: user_auth_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Juventus108
      TZ: 'Europe/Rome'
    ports:
      - '5434:5432'
    volumes:
      - user_management_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - geopathplanner-net

  user-management-pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin_user_management
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin123
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - '5050:80'
    depends_on:
      - user-management-db
    networks:
      - geopathplanner-net

networks:
  geopathplanner-net:
    driver: bridge

volumes:
  api_db_data:
  api_pgadmin_data:
  user_management_db_data:
    driver: local